
2021-06-14 18:52:16,460 INFO: errors [in C:\Users\Admin\PycharmProjects\01_fyyur\starter_code\app.py:508]
2021-06-14 23:29:07,544 INFO: errors [in C:\Users\Admin\PycharmProjects\01_fyyur\starter_code\app.py:567]
2021-06-15 19:20:36,594 INFO: errors [in C:\Users\Admin\PycharmProjects\01_fyyur\starter_code\app.py:566]
2021-06-15 19:23:50,119 INFO: errors [in C:\Users\Admin\PycharmProjects\01_fyyur\starter_code\app.py:566]
2021-06-15 19:23:58,900 INFO: errors [in C:\Users\Admin\PycharmProjects\01_fyyur\starter_code\app.py:566]
2021-06-15 19:24:05,096 ERROR: Exception on /venues [GET] [in C:\Program Files\Python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\relationships.py", line 2739, in _determine_joins
    self.primaryjoin = join_condition(
  File "<string>", line 2, in join_condition
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\sql\selectable.py", line 1204, in _join_condition
    raise exc.NoForeignKeysError(
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between 'Venue' and 'Show'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Program Files\Python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\PycharmProjects\01_fyyur\starter_code\app.py", line 114, in venues
    venuess = Venue.query.all()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\base.py", line 436, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\base.py", line 415, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\mapper.py", line 1874, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\mapper.py", line 3423, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\mapper.py", line 1891, in _post_configure_properties
    prop.init()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\interfaces.py", line 228, in init
    self.do_init()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\relationships.py", line 2137, in do_init
    self._setup_join_conditions()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\relationships.py", line 2233, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\relationships.py", line 2628, in __init__
    self._determine_joins()
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\orm\relationships.py", line 2761, in _determine_joins
    util.raise_(
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship Venue.shows - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
